services:
  postgres:
    image: postgres:16
    container_name: imdb_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT_ON_HOST:-5433}:5432"
    volumes:
      - imdb_pgdata:/var/lib/postgresql/data
      - ../sql/init:/docker-entrypoint-initdb.d:ro
      - ../sql:/sql:ro
      - ../data:/data
      - ../scripts:/scripts:ro
    command: >
      postgres -c work_mem=${PG_WORK_MEM:-64MB}
               -c maintenance_work_mem=${PG_MAINTENANCE_WORK_MEM:-512MB}
               -c max_wal_size=4GB
               -c shared_buffers=1GB

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: imdb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['localhost','localdomain','local','test','local.test']"

    ports:
      - "${PGADMIN_PORT_ON_HOST:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  imdb_pgdata:
    name: docker_imdb_pgdata
  pgadmin_data:
    name: docker_pgadmin_data